### ISSUE TITLE
Extension no longer functions on IMDB

### ISSUE THREAD

**Issue by ldblake** [anacrolix/imdbrt#14]
IMDB changed the site and the extension no longer works. Will there be an update? Thanks.

**Comment by anacrolix** [comment]
Thanks, I'll look into it shortly.

**Comment by ldblake** [comment]
The site seems to have been reverted back to how it was before, and the extension is functioning again. I would guess just watch the site for future changes.

**Comment by anacrolix** [comment]
Thanks for the heads-up.
