### ISSUE TITLE
Its not working after the IMDB page design update

### ISSUE THREAD

**Issue by ericlucio** [anacrolix/imdbrt#15]
Its not working after the IMDB page design update. Please dev, can you try to fix?

**Comment by anacrolix** [comment]
It's working for me, can you confirm you still have a problem?

**Comment by ha5hi5h** [comment]
Having the same issue. Chrome 47. Sample screenshot attached

![image](https://cloud.githubusercontent.com/assets/16464769/12020422/4c8bbb3e-adb7-11e5-98d4-0294a1663f9a.png)

**Comment by anacrolix** [comment]
Thanks for the screenshot. This could be difficult, my IMDB interface hasn't changed. I wonder what they're doing, if they're testing a new interface only on some users or countries.

**Comment by ha5hi5h** [comment]
where are you located? what can i help?

**Comment by rooban** [comment]
Same problem for me, located in Sweden

**Comment by sl4ppy** [comment]
Same issue here, located in the US.

**Comment by anacrolix** [comment]
Cheers guys, I'll take a look again soon.

**Comment by anacrolix** [comment]
Clearing my cookies moved me to the new interface.

**Comment by ha5hi5h** [comment]
any updates? loads more feedback on the google webstore

**Comment by anacrolix** [comment]
Should be fixed now.
