### ISSUE TITLE
An update on the underlying omdbAPI

### ISSUE THREAD

**Issue by kaptainkommie** [anacrolix/imdbrt#20]
According to responses by the owner of omdbAPI, the extended Rotten Tomatoes information is never coming back.

[https://github.com/omdbapi/OMDb-API/issues/5](https://github.com/omdbapi/OMDb-API/issues/5)

He will be adding the Metacritic and RT IDs for items to the JSON response at some point in the future. Perhaps we can use this to scrape the extended information from their sites. I'm not sure of the legality of this in different jurisdictions, but a recent court ruling against LinkedIn in the United States essentially says that it is legal to scrape publicly available information. [https://arstechnica.com/tech-policy/2017/08/court-rejects-linkedin-claim-that-unauthorized-scraping-is-hacking/](https://arstechnica.com/tech-policy/2017/08/court-rejects-linkedin-claim-that-unauthorized-scraping-is-hacking/)

That being said, if we were to implement scraping, the scrapes would be really be no different than a user visiting IMDB and then visiting RT or Metacritic site to check the score. It is not like the extension would be generating thousands and thousands of automated requests, it seems unlikely that RT would ever even take note.

**Comment by anacrolix** [comment]
The upstream script no longer uses omdbapi. Current issues with the extension not working are now tracked in #22 .
