### ISSUE TITLE
Chrome Extension: Not working

### ISSUE THREAD

**Issue by moviedino** [anacrolix/imdbrt#21]
Unfortunatelly the extension (4.0.2.2) is not working anymore.
I am using Chrome 65.0.3325.106 (Official Build) beta (64-bit) with no adblocking extensions.
The complete area of the extension below the imdb ratings dissapeared.
Perhaps the extension cannot handle the changed website design.
Can anyone have a look?

**By the way:** The script from Curtis Gibby (https://greasyfork.org/en/scripts/7158-imdb-add-rottentomatoes-info) now uses the Cinesift API to get the RT data. I did some research but could not find any information about the API!?

**Comment by anacrolix** [comment]
Thanks for the report. I'll update to Curtis' latest script and see if that helps.

**Comment by anacrolix** [comment]
Unfortunately it didn't help,  Cinesift is redirecting to flickmetrix.com. I'll continue to track this in #22 .
